"""Add horse_medical_records table

Revision ID: 7f4bda760caf
Revises: 
Create Date: 2025-12-05 23:14:37.209589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4bda760caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse_medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('checkup_date', sa.Date(), nullable=False),
    sa.Column('veterinarian', sa.String(length=100), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('next_checkup_date', sa.Date(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horse_medical_records')
    # ### end Alembic commands ###
